name: Semgrep SAST Scan

on:
  push:

jobs:
  semgrep:
    name: Run Semgrep SAST
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep scan
        run: semgrep scan --config auto .
